### PR TITLE
Add SassAsset

### PR DESCRIPTION
**Pull request by jgable**
I took a shot at adding a `SassAsset`.  I tried to keep it similar to the `LessAsset` coding style and functionality.  Same goes for the unit tests.

I had some trouble finding a good node sass compiler, the [node-sass](https://github.com/andrew/node-sass/issues) project seems to be unmaintained and has a problem with compressed output, so I wrote a little wrapper around the sass command line process.  It's a little slow, but seems to do the job.

Sorry about the package.json whitespace issues, all that should have changed in that file was adding a dependency on [node-sassy](https://github.com/jgable/node-sassy).

### CODE REVIEW

**Comment by techpines** [comment]
Awesome, let me take a look.  

I'm actually super glad that you didn't use node-sass, because it has binary dependencies.  :)

**Comment by noc7c9** [comment]
The `url(...)` rewriting code should probably be moved into `utils`, since its used for `LessAsset`, `StylusAsset` as well as this now.

**Comment by jgable** [comment]
I agree about the `url(...)` code.  I'd considered making a base compiled asset class to inherit from since they have similar core code.

I'd be happy to update with those changes if you'd like.

**Comment by techpines** [comment]
Yea, that would be awesome, I would say go with the utils approach, deep nested class hiearchies make me nervous. :)

**Comment by techpines** [comment]
Actually, I'm just gonna merge this now.  I can do the refactoring.

**Comment by techpines** [comment]
@jgable I have all of the sass stuff commented out in the latest release of asset-rack, because I couldn't get the tests to run.  Any ideas?

**Comment by jgable** [comment]
What are the errors you are getting?  When I clone this repo for myself and try to run `npm test` none of the tests run, not just the sass stuff.  Whereas my fork which hasn't pulled from here since submitting this PR, does.

**Comment by jgable** [comment]
There are a lot of problems with the check on the content-type header, it now has an appended `;charset=UTF-8` from easyrequest.  When I updated all those checks to include the charset, all the tests pass for me.

**Comment by techpines** [comment]
Yea, `master` branch is a little messy.  I just pushed up the code I'm running with all the sass stuff re-enabled.  

So if I clone from the current state, and do `npm test`, I'm getting this:

```
  1) a sass asset should work with .scss:
     Error: Sass exited with non-zero code: 127
      at ChildProcess.<anonymous> (/home/brad/techpines/asset-rack/node_modules/node-sassy/lib/SassExecuter.js:48:29)
      at ChildProcess.EventEmitter.emit (events.js:99:17)
      at Process._handle.onexit (child_process.js:678:10)
```

**Comment by noc7c9** [comment]
I just tried it myself and all the tests pass for me.
PS: I noticed that you haven't enabled the `utils.walk` tests, any reason for that?

**Comment by techpines** [comment]
Hmm.  What OS and node version are you running?

**Comment by techpines** [comment]
Oh yea, and utils.walk, I rearranged and forgot to add back, will fix :)

**Comment by noc7c9** [comment]
Ubuntu 12.10 and Node.js v0.8.14
I don't really know much about node-sassy or ruby gems in general; but I'm gonna take a wild guess and say that `node-sassy` can't find the sass executable, which probably needs to be in `PATH`.
@jgable does `node-sassy` install `sass`?

**Comment by techpines** [comment]
Oh it uses the gem.

If there is an outside dependency to ruby, then I think this should go outside of asset-rack.

If someone puts this in a separate repo, I'll link to it on the docs page.

**Comment by jgable** [comment]
`node-sassy` does not install `sass`, but it does rely on it being there.  Which it would have to be to use a sass asset anyway, there is no purely node implementation of the sass compiler.

To be clear; if you are using sass assets on your rack, you'd have to have the sass gem installed, but it does not keep other assets from being used without it.

**Comment by techpines** [comment]
I installed `sass`, and all tests pass!

I mean a lot of dev's that would be using sass, probably come from a ruby background, so maybe having to install gems won't be that big of a deal?

I'm somewhat hesitant to include something that has a big outside dependency, but you are right that it doesn't effect people that don't use it.

Unless there is someone else out there who doesn't like it, I'm just going to push the sass stuff live.

**Comment by noc7c9** [comment]
As long as you put a notice of the dependency on the `SassAsset` documentation I can't see it causing any problems.

@jgable perhaps you should consider having a `node-sassy` raise a clearer error message for that particular error code?
`Sass exited with non-zero code: 127` is very misleading, it seems as if it did find `sass` executable.

**Comment by jgable** [comment]
[Already added as a future enhancement](https://github.com/jgable/node-sassy/issues/1)

**Pull request merged**
