### PR TITLE
utils.walk method added; DynamicAssets class added; StaticAssets re-implemented to use DynamicAssets

### PR DESCRIPTION
**Pull request by noc7c9**
https://github.com/techpines/asset-rack/issues/38

Woo! That was fun :D
Just hope I didn't break anything...
(All the existing tests are passing though.)

So I've added a walk function

``` coffee
rack.utils.walk dirname, [options,] iterator [, callback]
```

As you can see I drew from the async api; and it works asynchronously.
Should I make a synchronous version as well?

> Note: in the end I didn't use `wrench-js` due to a few problems making the entire walk function asynchronous

eg:

``` coffee
walk '/somedir',
  ignoreFolders: true # folders won't be passed to the iterator
  filter: 'coffee' # only pass *.coffee files to the iterator; can also be a function
  , (file, done) -> # called for each file; done must be called
  , (err) -> # called after the last file (optional)
```

I've also added DynamicAssets which uses `walk` and StaticAssets now extends DynamicAssets.

``` coffee
new DynamicAssets
  type: StylusAsset
  filter: '.styl'
  dirname: '/styl'
  url: '/css'
  options:
    compress: true
    config: ->
      use nib()
```

---

Also I have a few details I need to clarify.
- While converting StaticAssets I made a class which is basically a single file version of StaticAssets

```
new StaticAsset
  url: '/hello-world.txt'
  filename: '/path/to/hello-world/file.txt'
```

Should I expose this? It might be useful to some users maybe?
- Should I make StaticAssets style classes for each of the builtin assets? ie. StylusAssets, LessAssets, etc.
- Which of the following styles should I use for passing arbitrary options the asset factory?

``` coffee
new DynamicAssets
  ...
  options: # via an options object...
    compress: true
```

``` coffee
new DynamicAssets
  ...
  compress: true # ...or directly to the constructor?
```

---

I'll be make some tests for the new additions a little later.

PS: Sorry for the wall of text :)

### CODE REVIEW

**Comment by techpines** [comment]
Wow!  This looks awesome!

Let me check this out, and then we'll get it merged.

There are a lot of people who are going to be happy about this one.  Much thanks @noc7c9

**Comment by techpines** [comment]
Hmm...

Now that I merged this, I realized that you weren't actually finished :) 

So I think the `StaticAsset` class is probably a little overkill, becuase this is equivalent just using the base class:

``` coffee
new Asset
  url: '/hello-world.txt'
  filename: fs.readFileSync '/path/to/hello-world/file.txt'
```

For `DynamicAssets` I like this for options:

``` coffee
new DynamicAssets
  ...
  options: # via an options object...
    compress: true
```

I think it makes it a little clearer that those options are getting passed down to the individual assets, and are not part of the top level dynamic asset.

Also, for all of the other plural assets like `StylusAssets`, `LessAssets`.  Someone had suggested something called `AutoAssets`, with the idea there that it would be sort of like an extension of the StaticAssets class that would automatically convert '.less', '.stylus' or whatever.

**Comment by noc7c9** [comment]
The `Asset` and `StaticAsset` classes have a small difference in that `Asset` decides mimetype via the url and `StaticAsset` decides via the filename. Doubt thats a big deal though.

As for `AutoAssets` are you thinking something like this?

``` coffee
walk (files, next) ->
  switch file.ext
    when 'styl' then StylusAsset
    when 'less' then LessAsset
    ...
    else StaticAsset
```

And how should I handle jade and angular assets? Both are meant to take directories of templates.

**Comment by techpines** [comment]
I think the `StaticAssets` vs `Asset` difference is a code relic. When I wrote `StaticAssets`, the base `Asset` class did not always do that auto mime type check.

Yea that's what I was thinking for the `AutoAssets`, it was @bitmage who had the suggestion so I'm not totally sure how that would be handled.  

Now that I think about it a little more, the idea of `AutoAssets` is cool but maybe the `DynamicAssets` class gets you pretty much to the same place, and there is a little less ambiguity.

**Comment by noc7c9** [comment]
So no real need for something like `AutoAssets` then. Can always add it later if need be.

**Comment by techpines** [comment]
Yea, for sure.

**Pull request merged**
