### PR TITLE
Some great features (incomplete)

### PR DESCRIPTION
**Pull request by mildsunrise**
Asset Rack is incredible. Really.
I have always been saying "I should write some asset manager to
do name cache busting", but I never found the time.
This library does this and more.

But I found that some features are missing for it to be really usable:
- [ ] Implement `relativeUrl` (the base for the next feature),
  which returns the URL of an asset relative to another asset.
- [ ] **Have a way to reference an asset** (i.e. an image) **from inside
  another asset** (like a Stylus stylesheet).
- [ ] [RequireJS](http://requirejs.org) is a module loader. It helps you
  organize your scripts and define dependencies between them.
  **And it has an optimizer** which concatenates scripts in the correct
  order, optimizes and optionally minimizes them.
  Asset-Rack should have some support for it.

And some other gotchas:
- <del>Be flexible. Don't _require_ some things to be present, make them optional.</del> See the discussion on #46.
- [x] (@noc7c9 did it in #46) Allow for more customization for the Stylus asset. That includes:
  - Ability to not use NIB. NIB is excellent, I always use it
    but there may be some people who prefers not to.
  - Custom configuration of the Stylus compiler used.
  
  To not break compatibility at all, I propose to add an option
  named `config`. It should be a function so we can `stylus.use(...)` it.
  **If not set, `nib()` is used instead** (if available).
- [ ] Proper documentation of the new features.

Also, why does `compress` default to `false`?
Come on, the static web is efficient. :rocket:

### CODE REVIEW

**Comment by techpines** [comment]
It's not documented, but both the Stylus and Less assets will find and replace urls if they are in the same rack together.  You just have to define your static assets first.

I'm still using Less, so any improvements to the Stylus asset would be great.

Also, `compress` defaults to false because it's the concept of defaulting to development mode.  In development mode you want your assets uncompressed, because you might want to look at them.

**Comment by mildsunrise** [comment]
> It's not documented, but both the Stylus and Less assets will find and replace urls if they are in the same rack together. You just have to define your static assets first.

Oops. Sorry I didn't notice it. Anyway this has a few caveats:
- Replacing URLs with a regexp is a _very bad_ idea that may harm someone.
- Stylus has an excelent API to define Stylus functions from JS side.
- URLs **should be relative**. Some CDNs apply a prefix to the files.
  Since you can't [always] predict the prefix until you deploy, relative
  URLs is the only way to go. And they're shorter!
- It needs documentation. :)

> Also, compress defaults to false because it's the concept of defaulting to development mode. In development mode you want your assets uncompressed, because you might want to look at them.

Yep, I understand. What about defaulting `compress` to `true` only if
the environment `== 'production'`? Just askin'.

**Comment by techpines** [comment]
I'm not very keen on the relative url scheme.  If there is a way to transparently do it, then that's fine, but I've avoided relative urls in every production app I've ever built.  Here's an article about using them:

http://yoast.com/relative-urls-issues/

True some CDN's may put you outside the root, but I kind of view that as a deficiency of the CDN.  Subdomains are cheap.  

Replacing urls via regex is not bad if you are sure that your regex is grabbing the right string.  Besides after talking with another guy.  A lot of people would prefer for url replacement to be handled transparently.  It would probably be a good idea to give people the ability to turn it off.  

Documentation and environment thing I agree with.

**Comment by mildsunrise** [comment]
> I'm not very keen on the relative url scheme. If there is a way to transparently do it, then that's fine, but I've avoided relative urls in every production app I've ever built.

This is interesting. It would of course be handled transparently.
On one side, the article doesn't say anything about relative URLs for assets.
And its use won't cause any SEO issues, since they aren't content.
Plus it's more compatible, flexible and a bit shorter.

---

> Replacing urls via regex is not bad if you are sure that your regex is grabbing the right string.

RegExps were not made for that kinda tasks (the ones which involve parsing).
For example, here:

``` css
@import url(/some/other.css);
```

Or here:

``` css
background-image: url("/some/other.css");
```

Or even here:

``` css
.fancy:before {
  content: 'The url (';
}
.fancy:after {
  content: ') is wrapped.';
}
```

Apply the regexp in any of these cases and :collision:! You're dead.

**Comment by techpines** [comment]
I think all of those examples would compile fine.  You would need to actually run it through asset-rack and find a real breakage, because it only replaces if it finds a valid url in the rack, and it only runs on the compiled css result.

Also, no regex for parsing?  Tell that to TJ, the guy who wrote Stylus:

https://github.com/LearnBoost/stylus/blob/master/lib/lexer.js

Also, I don't want to rain on the relative url parade.  Submit some code so I can get a better idea, of how it might work.  Although the whole problem of asset dependencies and url resolution is a fairly complex problem, so I mean there are gonna be tradeoffs between various solutions.

**Comment by mildsunrise** [comment]
Yep, I know, no damage would be made in this case,
but just to illustrate that a RegExp would incorrectly skip
(first two cases) or detect (last case) URLs.

> Also, no regex for parsing? Tell that to TJ, the guy who wrote Stylus:

I think we told him once, but wasn't much open to the change.

> Also, I don't want to rain on the relative url parade. Submit some code so I can get a better idea, of how it might work.

Ok. I'm gonna do that.

**Comment by binarykitchen** [comment]
+1 for "Have a way to reference an asset (i.e. an image) from inside another asset (like a Stylus stylesheet)."

**Comment by techpines** [comment]
@binarykitchen this already works, if you declare your `StaticAssets` before Stylus, then it will try and replace urls with the correct hashed urls.

Let me know if you have any issues with it.

**Comment by binarykitchen** [comment]
ah, it worked with `StaticAssets` like a charm. wonderful! thx

**Pull request closed without merging**
