### PR TITLE
wrote tests for DynamicAssets and utils.walk

### PR DESCRIPTION
**Pull request by noc7c9**
I wrote tests for `DynamicAssets` and `utils.walk`.

I also fixed a bunch of other tests that were incorrect and a few that broke with the last few commits (mainly due to switching to the `application/javascript` mimetype).

And I switched to using `mocha.opts`, hope thats alright.

### CODE REVIEW

**Comment by techpines** [comment]
@noc7c9 Thanks for all your help.

I'm thinking about writing a documentation page or tutorial about building custom assets.  I was wondering if you had any feedback on what you found difficult or confusing about about doing it yourself?

**Comment by noc7c9** [comment]
I found the whole process quite straight forward and easy. The only possible hiccup I can think of is waiting for each sub-asset to complete before emitting complete for the collection type assets.

Also I found that reading the code for the builtin assets was incredibly helpful, so you might want to include a trivial but _complete_ example in the tutorial.

One thing I believe you should add is setting a default mimetype at class level; seems like a good practice.

``` coffee
class SuperAwesomeAsset extends rack.Asset
    @mimetype: 'text/css' # <-- this here
```

**Comment by techpines** [comment]
Cool, thanks for the advice.

Yea, I agree about the sub-assets.  The only other way I thought to make that simpler is to do something like this:

``` coffee
create: (options) ->
    for filename in options.filenames
        @addAsset new rack.Asset 
            url: filename
            contents: fs.readFileSync(filename, 'utf8')
    @emit 'created'
```

Then under the covers maybe `@addAsset` could make sure to wait for the sub-assets to complete.  

That might be the best way to go about it.

**Comment by noc7c9** [comment]
Yes that looks excellent.
I'm guessing that any `@emit 'created'` calls would be ignored if `@addAsset` is called?

**Comment by techpines** [comment]
I think there might be edge cases where you are creating assets asynchronously with `@addAsset`, and it won't work correctly. For example the second asset here would never get built:

``` coffee
create: (options) ->
    @addAsset new rack.Asset()
    longRunningAysncOperation =>
        @addAsset new rack.Asset()  # Never gets called
```

Whereas if you emit created you can make sure that second asset is added.

``` coffee
create: (options) ->
    @addAsset new rack.Asset()
    longRunningAysncOperation =>
        @addAsset new rack.Asset()
        @emit 'created'
```

**Comment by noc7c9** [comment]
You're completely right but wouldn't that also be a premature `@emit 'created'`, for example when using with a `Rack`?

``` coffee
create: (options) ->
    @addAsset new AssetThatTakesForeverToBuild()
    @emit 'created'
    # now this collection would be marked as complete
    # even though the sub asset hasn't been built yet.
```

Probably would have to override the emit 'created' to not mark as complete if `@addAsset` was ever called.

**Comment by noc7c9** [comment]
Shall I take a crack at implementing this?

**Comment by techpines** [comment]
Definitely! 

I think you're right, that you would have to override the behavior of the callback for `emit 'created'`.

There's actually another trick that I use with the `Rack` class to make sure that the assets are not created before the rack is ready:

https://github.com/techpines/asset-rack/blob/master/lib/rack.coffee#L24
https://github.com/techpines/asset-rack/blob/master/lib/asset.coffee#L57

**Pull request merged**
