### PR TITLE
StaticAssets Supports Filtering and Uses Generalized FS Walker

### PR DESCRIPTION
**Pull request by bitmage**
See commit history for features added/bugs fixed.

This is mainly changes required to accomplish the processing pipeline for an application I'm building.  With this I can:
- Use StaticAssets to recursively walk through a directory
- Define a filter option which will limit what files get processed (which means I can separate the html files and not hash them)
- The directory walking functionality is generalized

There are a lot of changes here, so let me know how I should structure this and what fits/doesn't fit with your standards for the library.

### CODE REVIEW

**Comment by bitmage** [comment]
I've now added an asset for creating a map of hashed assets for AMD.  It basically arrives at the maps through a series of string replacements.  Brittle perhaps, but it works for me.  You can provide an optional 'paths' when creating the AMD asset - this accepts a format identical to the AMD config for paths, and it can be used to change the prefix for the maps.  Due to the way the string replacement works, you have to provide more specific paths first, then more general ones.  e.g. foo/bar/baz, then foo/bar.

I also changed JadeAsset and ClientAssets to use 'application/json' as their mimetypes.  The mime module in your dependencies defines the js extension to have 'application/json' so I did this to be consistent.

What's the best way to submit a plethora of changes like this?  Should I create separate branches so you can more easily pick through them?

**Comment by techpines** [comment]
Yea, it would probably be easier if you submitted a couple separate pull requests.

application/javascript is the correct mimetype, but most people including Google are still sending text/javascript for better browser compatibility.

**Comment by bitmage** [comment]
I don't know how to submit separate pull requests.  Do I use branches?

**Comment by techpines** [comment]
Yea, branch and then you can do a pull request for the branch.

**Comment by techpines** [comment]
Closing in favor of smaller pull requests.

**Pull request closed without merging**
