### PR TITLE
addAsset method added

### PR DESCRIPTION
**Pull request by noc7c9**
https://github.com/techpines/asset-rack/pull/52
A fairly simple implementation, the `created` handler waits for sub-assets to build before setting `@completed = true`

`@addAsset` is just sugar for `@assets.push`

### CODE REVIEW

**Comment by techpines** [comment]
@noc7c9 I think we should modify StaticAssets and DynamicAssets to use this before we merge this.  To make sure it works.

**Comment by noc7c9** [comment]
Done! and it works :D

**Comment by techpines** [comment]
Sweet!

**Comment by techpines** [comment]
Oh happy day!  This is merged, manually, but it's in there.  Thanks!

**Pull request closed without merging**
