### PR TITLE
Work on windows

### PR DESCRIPTION
**Pull request by noc7c9**
`asset-rack` didn't work when I cloned it on my work pc running windows. So here a fix to make it cross-platform and a few other changes.
- switched to `express` for testing since we don't need `socket.io`
- changed `package.json` scripts, npm prepends `./node_modules/.bin` to `PATH` so this works cross-platform
  - I have not changed the `postpublish` script because I don't know a cross platform way to delete a folder
- all tests are more consistent with each other
  - use beforeEach to setup `app`
  - use `#{fixturesDir}` in all tests
- moved the `DynamicAsset` test a bit.
- use `.skip` to disable the `SassAsset` tests, better than commenting out.
- added `lib` and `test` to `.npmignore`, no need all that as a dependency right?
- changed `coffee-script` into a `devDependency` for the same reason as above

### CODE REVIEW

**Comment by techpines** [comment]
What was the actual bug on windows?

**Comment by noc7c9** [comment]
`echo $(pwd) > /tmp/.pwd` in prepublish and building socket.io failed (due to missing ...er I can't remember what it was but the build was failing)

I also think `npm test` wasn't working. (Sorry I can't remember and I don't have access to a windows computer right now)

Basically I did this.

``` sh
$ git clone https://github.com/techpines/asset-rack.git
$ cd asset-rack
$ npm install
FAIL! build error
```

I know this would work if I were using cygwin and honestly the majority of this commit isn't windows related.
So just look the changes over.

Should I split the test changes to another pull request?

**Comment by techpines** [comment]
Yea, splitting them would be awesome.

**Comment by noc7c9** [comment]
Will do. So I'll close this an make another pull request.

**Pull request closed without merging**
