### PR TITLE
Fixing jade tests

### PR DESCRIPTION
**Pull request by johngeorgewright**
The jade tests have been failing for me... the fixtures needed a bit of a shuffle around.

### CODE REVIEW

**Comment by techpines** [comment]
I tried your tests and they failed for me on Linux/Ubuntu 12.04.

``` bash
git clone git@github.com:johngeorgewright/asset-rack.git
git pull origin fix-jade-tests
cd asset-rack
npm install
npm test
```

Basically, it's failing on that byte by byte file comparison, where it reads the fixture file and compares it to the response. 

What platform are you on?  I know you mentioned windows before.

**Comment by johngeorgewright** [comment]
Today I'm on Ubuntu 12.04 as well, but I was getting the same results in Windows 7 too. Maybe a node version difference?

``` sh
$ node -v
v0.8.19
```

For me, the files that are including in the response are being compiled in a different order.

**Comment by johngeorgewright** [comment]
Maybe the test should look for _matches_ in the response rather than an exact string? It's possible that the order in which the files are being added together could change dependant on node versions and platforms.

**Comment by techpines** [comment]
Hey I merged this, and then got rid of the actual file comparisons.

I think you're right, that the functionality is correct, but unfortunately the cross platform issues are causing "false" failures. 

The only thing I added was a test to make sure that the compressed version is smaller than the actual version.

If this is not fixed on your end let me know, and we can reopen.

**Comment by techpines** [comment]
But I think the other jade tests do cover _matches_ in the response.

**Comment by johngeorgewright** [comment]
Yep. Works for me. Ta very much.

**Pull request merged**
