### PR TITLE
Created Jade Templates won't work on IE <= 9 due syntax error issues

### PR DESCRIPTION
**Pull request by moellenbeck**
don't add a colon after the last entry of templates.

### CODE REVIEW

**Comment by techpines** [comment]
Cool, nice catch.  I think I've seen that issue before, much thanks!

**Comment by moellenbeck** [comment]
@techpines noprob - when would you release a new version?

**Comment by techpines** [comment]
I've been pretty slammed, so it's actually been a few weeks since we've had a new version.  Luckily, I've got some extra time this weekend so I'm gonna try and get it pushed out.

I'll drop a line on this thread when the new version is up.

Cheers

**Comment by moellenbeck** [comment]
nice - thank you.

cheers

**Pull request merged**
